### ISSUE TITLE
Error when running py index.py

### ISSUE THREAD

**Issue by andreibadescu** [yurtsiv/binomial-heap-visualizer#1]
Traceback (most recent call last):
  File "...\binomial-heap-visualizer\index.py", line 7, in <module>
    App(root)
  File "...\binomial-heap-visualizer\gui\app.py", line 14, in __init__
    master.wm_attributes('-zoomed', True)
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 2005, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: wrong # args: should be "wm attributes window ?-alpha ?double?? ?-transparentcolor ?color?? ?-disabled ?bool?? ?-fullscreen ?bool?? ?-toolwindow ?bool?? ?-topmost ?bool??"

What version of python did you use to run this ? Are there any modules that need to be installed ?

**Comment by andreibadescu** [comment]
> 

Made it work, opened a pull-request.
